export default {
  products: [
    {
      _id: 12,
      name: "Slim Shirt",
      category: "Shirt",
      image: "/img/d1.jpg",
      price: 99.99,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: 123,
      name: "Fit Shirt",
      category: "Shirt",
      image: "/img/d1.jpg",
      price: 69.69,
      brand: "Nike",
      rating: 7.5,
      numReviews: 17,
      countInStock: 16,
    },
    {
      _id: 124,
      name: "Best pants",
      category: "Pants",
      image: "/img/d1.jpg",
      price: 199.99,
      brand: "Nike",
      rating: 5.5,
      numReviews: 13,
      countInStock: 10,
    },
  ],
};
